Collections:
  - Name: Baseline_Plus
    Metadata:
      Training Data: CUB
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 1x V100 GPUs
    Paper: https://arxiv.org/abs/1904.04232
    README: configs/classification/baseline_plus/README.md

Models:
  - Name: baseline-plus_conv4_1xb64_cub_5way-1shot
    Metadata:
      Training Data: CUB
      Epochs: 200
      Batch Size: 64
    In Collection: Baseline_Plus
    Results:
      - Task: Few Shot Image Classification
        Dataset: CUB
        Metrics:
          Accuracy: 62.01
    Weights: https://download.openmmlab.com/mmfewshot/classification/baseline_plus/cub/baseline-plus_conv4_1xb64_cub_5way-1shot_20211120_100254-9d2e9021.pth
    Config: configs/classification/baseline_plus/cub/baseline-plus_conv4_1xb64_cub_5way-1shot.py
  - Name: baseline-plus_conv4_1xb64_cub_5way-5shot
    Metadata:
      Training Data: CUB
      Epochs: 200
      Batch Size: 64
    In Collection: Baseline_Plus
    Results:
      - Task: Few Shot Image Classification
        Dataset: CUB
        Metrics:
          Accuracy: 77.72
    Weights: https://download.openmmlab.com/mmfewshot/classification/baseline_plus/cub/baseline-plus_conv4_1xb64_cub_5way-1shot_20211120_100254-9d2e9021.pth
    Config: configs/classification/baseline_plus/cub/baseline-plus_conv4_1xb64_cub_5way-5shot.py
  - Name: baseline-plus_resnet12_1xb64_cub_5way-1shot
    Metadata:
      Training Data: CUB
      Epochs: 200
      Batch Size: 64
    In Collection: Baseline_Plus
    Results:
      - Task: Few Shot Image Classification
        Dataset: CUB
        Metrics:
          Accuracy: 75.25
    Weights: https://download.openmmlab.com/mmfewshot/classification/baseline_plus/cub/baseline-plus_resnet12_1xb64_cub_5way-1shot_20211120_100254-143f4d7a.pth
    Config: configs/classification/baseline_plus/cub/baseline-plus_resnet12_1xb64_cub_5way-1shot.py
  - Name: baseline-plus_resnet12_1xb64_cub_5way-5shot
    Metadata:
      Training Data: CUB
      Epochs: 200
      Batch Size: 64
    In Collection: Baseline_Plus
    Results:
      - Task: Few Shot Image Classification
        Dataset: CUB
        Metrics:
          Accuracy: 89.85
    Weights: https://download.openmmlab.com/mmfewshot/classification/baseline_plus/cub/baseline-plus_resnet12_1xb64_cub_5way-1shot_20211120_100254-143f4d7a.pth
    Config: configs/classification/baseline_plus/cub/baseline-plus_resnet12_1xb64_cub_5way-5shot.py
