Collections:
  - Name: Baseline_Plus
    Metadata:
      Training Data: Tiered-ImageNet
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 1x V100 GPUs
    Paper: https://arxiv.org/abs/1904.04232
    README: configs/classification/baseline_plus/README.md

Models:
  - Name: baseline-plus_conv4_1xb64_tiered-imagenet_5way-1shot
    Metadata:
      Training Data: Tiered-ImageNet
      Epochs: 100
      Batch Size: 64
    In Collection: Baseline_Plus
    Results:
      - Task: Few Shot Image Classification
        Dataset: Tiered-ImageNet
        Metrics:
          Accuracy: 51.49
    Weights: https://download.openmmlab.com/mmfewshot/classification/baseline_plus/tiered_imagenet/baseline-plus_conv4_1xb64_tiered-imagenet_5way-1shot_20211120_100254-85eb4e29.pth
    Config: configs/classification/baseline_plus/tiered_imagenet/baseline-plus_conv4_1xb64_tiered-imagenet_5way-1shot.py
  - Name: baseline-plus_conv4_1xb64_tiered-imagenet_5way-5shot
    Metadata:
      Training Data: Tiered-ImageNet
      Epochs: 100
      Batch Size: 64
    In Collection: Baseline_Plus
    Results:
      - Task: Few Shot Image Classification
        Dataset: Tiered-ImageNet
        Metrics:
          Accuracy: 70.96
    Weights: https://download.openmmlab.com/mmfewshot/classification/baseline_plus/tiered_imagenet/baseline-plus_conv4_1xb64_tiered-imagenet_5way-1shot_20211120_100254-85eb4e29.pth
    Config: configs/classification/baseline_plus/tiered_imagenet/baseline-plus_conv4_1xb64_tiered-imagenet_5way-5shot.py
  - Name: baseline-plus_resnet12_1xb64_tiered-imagenet_5way-1shot
    Metadata:
      Training Data: Tiered-ImageNet
      Epochs: 100
      Batch Size: 64
    In Collection: Baseline_Plus
    Results:
      - Task: Few Shot Image Classification
        Dataset: Tiered-ImageNet
        Metrics:
          Accuracy: 67.26
    Weights: https://download.openmmlab.com/mmfewshot/classification/baseline_plus/tiered_imagenet/baseline-plus_resnet12_1xb64_tiered-imagenet_5way-1shot_20211120_100254-5fbf7c45.pth
    Config: configs/classification/baseline_plus/tiered_imagenet/baseline-plus_resnet12_1xb64_tiered-imagenet_5way-1shot.py
  - Name: baseline-plus_resnet12_1xb64_tiered-imagenet_5way-5shot
    Metadata:
      Training Data: Tiered-ImageNet
      Epochs: 100
      Batch Size: 64
    In Collection: Baseline_Plus
    Results:
      - Task: Few Shot Image Classification
        Dataset: Tiered-ImageNet
        Metrics:
          Accuracy: 84.4
    Weights: https://download.openmmlab.com/mmfewshot/classification/baseline_plus/tiered_imagenet/baseline-plus_resnet12_1xb64_tiered-imagenet_5way-1shot_20211120_100254-5fbf7c45.pth
    Config: configs/classification/baseline_plus/tiered_imagenet/baseline-plus_resnet12_1xb64_tiered-imagenet_5way-5shot.py
