Collections:
  - Name: Neg-Margin
    Metadata:
      Training Data: Tiered-ImageNet
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 1x V100 GPUs
    Paper: https://arxiv.org/abs/1003.12060
    README: configs/classification/neg_margin/README.md

Models:
  - Name: neg-margin_cosine_conv4_1xb64_tiered-imagenet_5way-1shot
    Metadata:
      Training Data: Tiered-ImageNet
      Epochs: 100
      Batch Size: 64
    In Collection: Neg-Margin
    Results:
      - Task: Few Shot Image Classification
        Dataset: Tiered-ImageNet
        Metrics:
          Accuracy: 54.07
    Weights: https://download.openmmlab.com/mmfewshot/classification/neg_margin/tiered_imagenet/neg-margin_cosine_conv4_1xb64_tiered-imagenet_5way-1shot_20211120_110238-7a81ac2a.pth
    Config: configs/classification/neg_margin/tiered_imagenet/neg-margin_cosine_conv4_1xb64_tiered-imagenet_5way-1shot.py
  - Name: neg-margin_cosine_conv4_1xb64_tiered-imagenet_5way-5shot
    Metadata:
      Training Data: Tiered-ImageNet
      Epochs: 100
      Batch Size: 64
    In Collection: Neg-Margin
    Results:
      - Task: Few Shot Image Classification
        Dataset: Tiered-ImageNet
        Metrics:
          Accuracy: 70.25
    Weights: https://download.openmmlab.com/mmfewshot/classification/neg_margin/tiered_imagenet/neg-margin_cosine_conv4_1xb64_tiered-imagenet_5way-1shot_20211120_110238-7a81ac2a.pth
    Config: configs/classification/neg_margin/tiered_imagenet/neg-margin_cosine_conv4_1xb64_tiered-imagenet_5way-5shot.py
  - Name: neg-margin_cosine_resnet12_1xb64_tiered-imagenet_5way-1shot
    Metadata:
      Training Data: Tiered-ImageNet
      Epochs: 100
      Batch Size: 64
    In Collection: Neg-Margin
    Results:
      - Task: Few Shot Image Classification
        Dataset: Tiered-ImageNet
        Metrics:
          Accuracy: 65.88
    Weights: https://download.openmmlab.com/mmfewshot/classification/neg_margin/tiered_imagenet/neg-margin_cosine_resnet12_1xb64_tiered-imagenet_5way-1shot_20211120_111912-344342e6.pth
    Config: configs/classification/neg_margin/tiered_imagenet/neg-margin_cosine_resnet12_1xb64_tiered-imagenet_5way-1shot.py
  - Name: neg-margin_cosine_resnet12_1xb64_tiered-imagenet_5way-5shot
    Metadata:
      Training Data: Tiered-ImageNet
      Epochs: 100
      Batch Size: 64
    In Collection: Neg-Margin
    Results:
      - Task: Few Shot Image Classification
        Dataset: Tiered-ImageNet
        Metrics:
          Accuracy: 81.06
    Weights: https://download.openmmlab.com/mmfewshot/classification/neg_margin/tiered_imagenet/neg-margin_cosine_resnet12_1xb64_tiered-imagenet_5way-1shot_20211120_111912-344342e6.pth
    Config: configs/classification/neg_margin/tiered_imagenet/neg-margin_cosine_resnet12_1xb64_tiered-imagenet_5way-5shot.py
