Collections:
  - Name: Baseline
    Metadata:
      Training Data: CUB
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 1x V100 GPUs
    Paper: https://arxiv.org/abs/1904.04232
    README: configs/classification/baseline/README.md

Models:
  - Name: baseline_conv4_1xb64_cub_5way-1shot
    Metadata:
      Training Data: CUB
      Epochs: 200
      Batch Size: 64
    In Collection: Baseline
    Results:
      - Task: Few Shot Image Classification
        Dataset: CUB
        Metrics:
          Accuracy: 47.73
    Weights: https://download.openmmlab.com/mmfewshot/classification/baseline/cub/baseline_conv4_1xb64_cub_5way-1shot_20211120_095923-3a346523.pth
    Config: configs/classification/baseline/cub/baseline_conv4_1xb64_cub_5way-1shot.py
  - Name: baseline_conv4_1xb64_cub_5way-5shot
    Metadata:
      Training Data: CUB
      Epochs: 200
      Batch Size: 64
    In Collection: Baseline
    Results:
      - Task: Few Shot Image Classification
        Dataset: CUB
        Metrics:
          Accuracy: 68.77
    Weights: https://download.openmmlab.com/mmfewshot/classification/baseline/cub/baseline_conv4_1xb64_cub_5way-1shot_20211120_095923-3a346523.pth
    Config: configs/classification/baseline/cub/baseline_conv4_1xb64_cub_5way-5shot.py
  - Name: baseline_resnet12_1xb64_cub_5way-1shot
    Metadata:
      Training Data: CUB
      Epochs: 200
      Batch Size: 64
    In Collection: Baseline
    Results:
      - Task: Few Shot Image Classification
        Dataset: CUB
        Metrics:
          Accuracy: 71.85
    Weights: https://download.openmmlab.com/mmfewshot/classification/baseline/cub/baseline_resnet12_1xb64_cub_5way-1shot_20211120_095923-f1d13cf6.pth
    Config: configs/classification/baseline/cub/baseline_resnet12_1xb64_cub_5way-1shot.py
  - Name: baseline_resnet12_1xb64_cub_5way-5shot
    Metadata:
      Training Data: CUB
      Epochs: 200
      Batch Size: 64
    In Collection: Baseline
    Results:
      - Task: Few Shot Image Classification
        Dataset: CUB
        Metrics:
          Accuracy: 88.09
    Weights: https://download.openmmlab.com/mmfewshot/classification/baseline/cub/baseline_resnet12_1xb64_cub_5way-1shot_20211120_095923-f1d13cf6.pth
    Config: configs/classification/baseline/cub/baseline_resnet12_1xb64_cub_5way-5shot.py
