Collections:
  - Name: Matching-Net
    Metadata:
      Training Data: Mini-ImageNet
      Training Techniques:
        - Adam
      Training Resources: 1x V100 GPUs
    Paper: https://arxiv.org/abs/1606.04080
    README: configs/classification/matching_net/README.md

Models:
  - Name: matching-net_conv4_1xb105_mini-imagenet_5way-1shot
    Metadata:
      Training Data: Mini-ImageNet
      Batch Size: 105
    In Collection: Matching-Net
    Results:
      - Task: Few Shot Image Classification
        Dataset: Mini-ImageNet
        Metrics:
          Accuracy: 53.35
    Weights: https://download.openmmlab.com/mmfewshot/classification/matching_net/mini_imagenet/matching-net_conv4_1xb105_mini-imagenet_5way-1shot_20211120_100611-cfc24845.pth
    Config: configs/classification/matching_net/mini_imagenet/matching-net_conv4_1xb105_mini-imagenet_5way-1shot.py
  - Name: matching-net_conv4_1xb105_mini-imagenet_5way-5shot
    Metadata:
      Training Data: Mini-ImageNet
      Batch Size: 105
    In Collection: Matching-Net
    Results:
      - Task: Few Shot Image Classification
        Dataset: Mini-ImageNet
        Metrics:
          Accuracy: 66.3
    Weights: https://download.openmmlab.com/mmfewshot/classification/matching_net/mini_imagenet/matching-net_conv4_1xb105_mini-imagenet_5way-1shot_20211120_100611-cfc24845.pth
    Config: configs/classification/matching_net/mini_imagenet/matching-net_conv4_1xb105_mini-imagenet_5way-5shot.py
  - Name: matching-net_resnet12_1xb105_mini-imagenet_5way-1shot
    Metadata:
      Training Data: Mini-ImageNet
      Batch Size: 105
    In Collection: Matching-Net
    Results:
      - Task: Few Shot Image Classification
        Dataset: Mini-ImageNet
        Metrics:
          Accuracy: 59.3
    Weights: https://download.openmmlab.com/mmfewshot/classification/matching_net/mini_imagenet/matching-net_resnet12_1xb105_mini-imagenet_5way-1shot_20211120_100611-62e83016.pth
    Config: configs/classification/matching_net/mini_imagenet/matching-net_resnet12_1xb105_mini-imagenet_5way-1shot.py
  - Name: matching-net_resnet12_1xb105_mini-imagenet_5way-5shot
    Metadata:
      Training Data: Mini-ImageNet
      Batch Size: 105
    In Collection: Matching-Net
    Results:
      - Task: Few Shot Image Classification
        Dataset: Mini-ImageNet
        Metrics:
          Accuracy: 72.63
    Weights: https://download.openmmlab.com/mmfewshot/classification/matching_net/mini_imagenet/matching-net_resnet12_1xb105_mini-imagenet_5way-1shot_20211120_100611-62e83016.pth
    Config: configs/classification/matching_net/mini_imagenet/matching-net_resnet12_1xb105_mini-imagenet_5way-5shot.py
